apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
      - name: hello
        image: azmassage/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: hello

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  annotations:
    service.beta.kubernetes.io/load-balancer-source-ranges: "172.0.0.0/8, 10.0.0.0/8"
spec:
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31110
  selector:
    app: hello
    tier: hello
  type: LoadBalancer
